apiVersion: v1
kind: Pod
metadata:
  name: jnlp-dind-pod
  labels:
    app: jnlp-dind
spec:
  containers:
    - name: jnlp
      image: brymat24/jnlp-dind:latest
      args: ['${computer.jnlpmac}', '${computer.name}']
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
    - name: docker-daemon
      image: docker:24-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
