apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: jnlp
      image: brymat24/jnlp-dind
      args: ['${computer.jnlpmac}', '${computer.name}']
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
    - name: docker
      image: docker:20.10.7-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command:
        - dockerd
      args:
        - --host=tcp://0.0.0.0:2375
        - --host=unix:///var/run/docker.sock
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}