apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: 'alpine:latest'
    command: ["/bin/sh", "-c"]
    args: [
      "apk add --no-cache docker-cli && while true; do sleep 30; done;"
    ]
    env:
    - name: DOCKER_HOST
      value: "tcp://localhost:2375"
    securityContext:
      privileged: true
  - name: docker
    image: docker:20.10.7-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    command:
    - dockerd
    args:
    - --host=tcp://0.0.0.0:2375
    - --host=unix:///var/run/docker.sock
    readinessProbe:
      httpGet:
        path: /_ping
        port: 2375
      initialDelaySeconds: 5
      periodSeconds: 2
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
