apiVersion: v1
kind: Pod
metadata:
  name: jnlp-dind-pod
  labels:
    app: jnlp-dind
spec:
  containers:
    - name: jnlp
      image: brymat24/jnlp-dind:latest
      args: ['${computer.jnlpmac}', '${computer.name}']
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
        - name: JENKINS_URL
          value: http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:8080
        - name: JENKINS_TUNNEL
          value: jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000
        - name: JENKINS_AGENT_WORKDIR
          value: "/home/jenkins/agent"
    - name: docker-daemon
      image: docker:24-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
