apiVersion: v1
kind: Pod
metadata:
  name: jnlp-dind-pod
  labels:
    app: jnlp-dind
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11-1
      args: ['${computer.jnlpmac}', '${computer.name}']
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
      command:
        - sh
        - -c
        - |
          apt-get update && \
          apt-get install -y docker.io && \
          while true; do sleep 30; done
    - name: docker-daemon
      image: docker:24-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
